/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.plt;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int midpform=0x7f040000;
        public static final int midpgauge=0x7f040001;
        public static final int midpgauge_label=0x7f040002;
        public static final int midpgauge_progressbar=0x7f040003;
        public static final int midplist=0x7f040004;
        public static final int midplistitem=0x7f040005;
        public static final int midplistitem_image=0x7f040006;
        public static final int midplistitem_text=0x7f040007;
        public static final int midpstringitem=0x7f040008;
        public static final int midpstringitem_label=0x7f040009;
        public static final int midpstringitem_value=0x7f04000a;
    }
    public static final class layout {
        public static final int main=0x7f020000;
        public static final int midpform=0x7f020001;
        public static final int midpgauge=0x7f020002;
        public static final int midplist=0x7f020003;
        public static final int midplistitem=0x7f020004;
        public static final int midpstringitem=0x7f020005;
        public static final int splash=0x7f020006;
    }
    public static final class string {
        public static final int app_name=0x7f030000;
    }
}
