// This is automatically generated by bootstrap-js-compiler.ss
// Please don't hand-edit this file.

var effect_colon_none = function () { plt.Kernel.Struct.call(this, "make-effect:none", []); };
effect_colon_none.prototype = new plt.Kernel.Struct();

var make_dash_effect_colon_none = function () { return new effect_colon_none(); };


var effect_colon_none_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_none; };

var effect_colon_beep = function () { plt.Kernel.Struct.call(this, "make-effect:beep", []); };
effect_colon_beep.prototype = new plt.Kernel.Struct();

var make_dash_effect_colon_beep = function () { return new effect_colon_beep(); };


var effect_colon_beep_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_beep; };

var effect_colon_play_dash_dtmf_dash_tone = function (tone,duration) { plt.Kernel.Struct.call(this, "make-effect:play-dtmf-tone", [tone,duration]);this.tone = tone;
this.duration = duration; };
effect_colon_play_dash_dtmf_dash_tone.prototype = new plt.Kernel.Struct();

var make_dash_effect_colon_play_dash_dtmf_dash_tone = function (id0,id1) { return new effect_colon_play_dash_dtmf_dash_tone(id0,id1); };
var effect_colon_play_dash_dtmf_dash_tone_dash_tone = function(obj) {
     if (effect_colon_play_dash_dtmf_dash_tone_question_ (obj)) {
        return obj.tone;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect_colon_play_dash_dtmf_dash_tone_dash_tone: not a effect:play-dtmf-tone: ~s', [obj]));
     }
};

var effect_colon_play_dash_dtmf_dash_tone_dash_duration = function(obj) {
     if (effect_colon_play_dash_dtmf_dash_tone_question_ (obj)) {
        return obj.duration;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect_colon_play_dash_dtmf_dash_tone_dash_duration: not a effect:play-dtmf-tone: ~s', [obj]));
     }
};

var set_dash_effect_colon_play_dash_dtmf_dash_tone_dash_tone_bang_ = function(obj,newVal) {
	 if (effect_colon_play_dash_dtmf_dash_tone_question_ (obj)) {
		obj.tone = newVal;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_play_dash_dtmf_dash_tone_dash_tone_bang_: not a effect:play-dtmf-tone: ~s', [obj]));
     }
};

var set_dash_effect_colon_play_dash_dtmf_dash_tone_dash_duration_bang_ = function(obj,newVal) {
	 if (effect_colon_play_dash_dtmf_dash_tone_question_ (obj)) {
		obj.duration = newVal;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_play_dash_dtmf_dash_tone_dash_duration_bang_: not a effect:play-dtmf-tone: ~s', [obj]));
     }
};

var effect_colon_play_dash_dtmf_dash_tone_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_play_dash_dtmf_dash_tone; };

var effect_colon_send_dash_sms = function (address,msg) { plt.Kernel.Struct.call(this, "make-effect:send-sms", [address,msg]);this.address = address;
this.msg = msg; };
effect_colon_send_dash_sms.prototype = new plt.Kernel.Struct();

var make_dash_effect_colon_send_dash_sms = function (id0,id1) { return new effect_colon_send_dash_sms(id0,id1); };
var effect_colon_send_dash_sms_dash_address = function(obj) {
     if (effect_colon_send_dash_sms_question_ (obj)) {
        return obj.address;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect_colon_send_dash_sms_dash_address: not a effect:send-sms: ~s', [obj]));
     }
};

var effect_colon_send_dash_sms_dash_msg = function(obj) {
     if (effect_colon_send_dash_sms_question_ (obj)) {
        return obj.msg;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect_colon_send_dash_sms_dash_msg: not a effect:send-sms: ~s', [obj]));
     }
};

var set_dash_effect_colon_send_dash_sms_dash_address_bang_ = function(obj,newVal) {
	 if (effect_colon_send_dash_sms_question_ (obj)) {
		obj.address = newVal;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_send_dash_sms_dash_address_bang_: not a effect:send-sms: ~s', [obj]));
     }
};

var set_dash_effect_colon_send_dash_sms_dash_msg_bang_ = function(obj,newVal) {
	 if (effect_colon_send_dash_sms_question_ (obj)) {
		obj.msg = newVal;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_send_dash_sms_dash_msg_bang_: not a effect:send-sms: ~s', [obj]));
     }
};

var effect_colon_send_dash_sms_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_send_dash_sms; };

var playlist_dash_sound = function (playlist) { plt.Kernel.Struct.call(this, "make-playlist-sound", [playlist]);this.playlist = playlist; };
playlist_dash_sound.prototype = new plt.Kernel.Struct();

var make_dash_playlist_dash_sound = function (id0) { return new playlist_dash_sound(id0); };
var playlist_dash_sound_dash_playlist = function(obj) {
     if (playlist_dash_sound_question_ (obj)) {
        return obj.playlist;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('playlist_dash_sound_dash_playlist: not a playlist-sound: ~s', [obj]));
     }
};

var set_dash_playlist_dash_sound_dash_playlist_bang_ = function(obj,newVal) {
	 if (playlist_dash_sound_question_ (obj)) {
		obj.playlist = newVal;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_playlist_dash_sound_dash_playlist_bang_: not a playlist-sound: ~s', [obj]));
     }
};

var playlist_dash_sound_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof playlist_dash_sound; };

var sound_question_ = function(x) { return ((plt.Kernel.setLastLoc("offset=0 line=0 span=0 id=\"\"")   && plt.Kernel.string_question_(x))||(plt.Kernel.setLastLoc("offset=0 line=0 span=0 id=\"\"")   && playlist_dash_sound_question_(x))); };
var effect_colon_play_dash_sound = function (sound) { plt.Kernel.Struct.call(this, "make-effect:play-sound", [sound]);this.sound = sound; };
effect_colon_play_dash_sound.prototype = new plt.Kernel.Struct();

var make_dash_effect_colon_play_dash_sound = function (id0) { return new effect_colon_play_dash_sound(id0); };
var effect_colon_play_dash_sound_dash_sound = function(obj) {
     if (effect_colon_play_dash_sound_question_ (obj)) {
        return obj.sound;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect_colon_play_dash_sound_dash_sound: not a effect:play-sound: ~s', [obj]));
     }
};

var set_dash_effect_colon_play_dash_sound_dash_sound_bang_ = function(obj,newVal) {
	 if (effect_colon_play_dash_sound_question_ (obj)) {
		obj.sound = newVal;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_play_dash_sound_dash_sound_bang_: not a effect:play-sound: ~s', [obj]));
     }
};

var effect_colon_play_dash_sound_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_play_dash_sound; };

var effect_colon_pause_dash_sound = function (sound) { plt.Kernel.Struct.call(this, "make-effect:pause-sound", [sound]);this.sound = sound; };
effect_colon_pause_dash_sound.prototype = new plt.Kernel.Struct();

var make_dash_effect_colon_pause_dash_sound = function (id0) { return new effect_colon_pause_dash_sound(id0); };
var effect_colon_pause_dash_sound_dash_sound = function(obj) {
     if (effect_colon_pause_dash_sound_question_ (obj)) {
        return obj.sound;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect_colon_pause_dash_sound_dash_sound: not a effect:pause-sound: ~s', [obj]));
     }
};

var set_dash_effect_colon_pause_dash_sound_dash_sound_bang_ = function(obj,newVal) {
	 if (effect_colon_pause_dash_sound_question_ (obj)) {
		obj.sound = newVal;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_pause_dash_sound_dash_sound_bang_: not a effect:pause-sound: ~s', [obj]));
     }
};

var effect_colon_pause_dash_sound_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_pause_dash_sound; };

var effect_colon_stop_dash_sound = function (sound) { plt.Kernel.Struct.call(this, "make-effect:stop-sound", [sound]);this.sound = sound; };
effect_colon_stop_dash_sound.prototype = new plt.Kernel.Struct();

var make_dash_effect_colon_stop_dash_sound = function (id0) { return new effect_colon_stop_dash_sound(id0); };
var effect_colon_stop_dash_sound_dash_sound = function(obj) {
     if (effect_colon_stop_dash_sound_question_ (obj)) {
        return obj.sound;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect_colon_stop_dash_sound_dash_sound: not a effect:stop-sound: ~s', [obj]));
     }
};

var set_dash_effect_colon_stop_dash_sound_dash_sound_bang_ = function(obj,newVal) {
	 if (effect_colon_stop_dash_sound_question_ (obj)) {
		obj.sound = newVal;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_stop_dash_sound_dash_sound_bang_: not a effect:stop-sound: ~s', [obj]));
     }
};

var effect_colon_stop_dash_sound_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_stop_dash_sound; };

var effect_colon_set_dash_sound_dash_volume = function (volume) { plt.Kernel.Struct.call(this, "make-effect:set-sound-volume", [volume]);this.volume = volume; };
effect_colon_set_dash_sound_dash_volume.prototype = new plt.Kernel.Struct();

var make_dash_effect_colon_set_dash_sound_dash_volume = function (id0) { return new effect_colon_set_dash_sound_dash_volume(id0); };
var effect_colon_set_dash_sound_dash_volume_dash_volume = function(obj) {
     if (effect_colon_set_dash_sound_dash_volume_question_ (obj)) {
        return obj.volume;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect_colon_set_dash_sound_dash_volume_dash_volume: not a effect:set-sound-volume: ~s', [obj]));
     }
};

var set_dash_effect_colon_set_dash_sound_dash_volume_dash_volume_bang_ = function(obj,newVal) {
	 if (effect_colon_set_dash_sound_dash_volume_question_ (obj)) {
		obj.volume = newVal;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_set_dash_sound_dash_volume_dash_volume_bang_: not a effect:set-sound-volume: ~s', [obj]));
     }
};

var effect_colon_set_dash_sound_dash_volume_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_set_dash_sound_dash_volume; };

var effect_colon_raise_dash_sound_dash_volume = function () { plt.Kernel.Struct.call(this, "make-effect:raise-sound-volume", []); };
effect_colon_raise_dash_sound_dash_volume.prototype = new plt.Kernel.Struct();

var make_dash_effect_colon_raise_dash_sound_dash_volume = function () { return new effect_colon_raise_dash_sound_dash_volume(); };


var effect_colon_raise_dash_sound_dash_volume_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_raise_dash_sound_dash_volume; };

var effect_colon_lower_dash_sound_dash_volume = function () { plt.Kernel.Struct.call(this, "make-effect:lower-sound-volume", []); };
effect_colon_lower_dash_sound_dash_volume.prototype = new plt.Kernel.Struct();

var make_dash_effect_colon_lower_dash_sound_dash_volume = function () { return new effect_colon_lower_dash_sound_dash_volume(); };


var effect_colon_lower_dash_sound_dash_volume_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_lower_dash_sound_dash_volume; };

var effect_colon_set_dash_wake_dash_lock = function (locks) { plt.Kernel.Struct.call(this, "make-effect:set-wake-lock", [locks]);this.locks = locks; };
effect_colon_set_dash_wake_dash_lock.prototype = new plt.Kernel.Struct();

var make_dash_effect_colon_set_dash_wake_dash_lock = function (id0) { return new effect_colon_set_dash_wake_dash_lock(id0); };
var effect_colon_set_dash_wake_dash_lock_dash_locks = function(obj) {
     if (effect_colon_set_dash_wake_dash_lock_question_ (obj)) {
        return obj.locks;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect_colon_set_dash_wake_dash_lock_dash_locks: not a effect:set-wake-lock: ~s', [obj]));
     }
};

var set_dash_effect_colon_set_dash_wake_dash_lock_dash_locks_bang_ = function(obj,newVal) {
	 if (effect_colon_set_dash_wake_dash_lock_question_ (obj)) {
		obj.locks = newVal;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_set_dash_wake_dash_lock_dash_locks_bang_: not a effect:set-wake-lock: ~s', [obj]));
     }
};

var effect_colon_set_dash_wake_dash_lock_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_set_dash_wake_dash_lock; };

var effect_colon_release_dash_wake_dash_lock = function () { plt.Kernel.Struct.call(this, "make-effect:release-wake-lock", []); };
effect_colon_release_dash_wake_dash_lock.prototype = new plt.Kernel.Struct();

var make_dash_effect_colon_release_dash_wake_dash_lock = function () { return new effect_colon_release_dash_wake_dash_lock(); };


var effect_colon_release_dash_wake_dash_lock_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_release_dash_wake_dash_lock; };

var effect_colon_pick_dash_playlist = function (update_dash_f) { plt.Kernel.Struct.call(this, "make-effect:pick-playlist", [update_dash_f]);this.update_dash_f = update_dash_f; };
effect_colon_pick_dash_playlist.prototype = new plt.Kernel.Struct();

var make_dash_effect_colon_pick_dash_playlist = function (id0) { return new effect_colon_pick_dash_playlist(id0); };
var effect_colon_pick_dash_playlist_dash_update_dash_f = function(obj) {
     if (effect_colon_pick_dash_playlist_question_ (obj)) {
        return obj.update_dash_f;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect_colon_pick_dash_playlist_dash_update_dash_f: not a effect:pick-playlist: ~s', [obj]));
     }
};

var set_dash_effect_colon_pick_dash_playlist_dash_update_dash_f_bang_ = function(obj,newVal) {
	 if (effect_colon_pick_dash_playlist_question_ (obj)) {
		obj.update_dash_f = newVal;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_pick_dash_playlist_dash_update_dash_f_bang_: not a effect:pick-playlist: ~s', [obj]));
     }
};

var effect_colon_pick_dash_playlist_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_pick_dash_playlist; };

var effect_colon_pick_dash_random = function (n,update_dash_f) { plt.Kernel.Struct.call(this, "make-effect:pick-random", [n,update_dash_f]);this.n = n;
this.update_dash_f = update_dash_f; };
effect_colon_pick_dash_random.prototype = new plt.Kernel.Struct();

var make_dash_effect_colon_pick_dash_random = function (id0,id1) { return new effect_colon_pick_dash_random(id0,id1); };
var effect_colon_pick_dash_random_dash_n = function(obj) {
     if (effect_colon_pick_dash_random_question_ (obj)) {
        return obj.n;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect_colon_pick_dash_random_dash_n: not a effect:pick-random: ~s', [obj]));
     }
};

var effect_colon_pick_dash_random_dash_update_dash_f = function(obj) {
     if (effect_colon_pick_dash_random_question_ (obj)) {
        return obj.update_dash_f;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect_colon_pick_dash_random_dash_update_dash_f: not a effect:pick-random: ~s', [obj]));
     }
};

var set_dash_effect_colon_pick_dash_random_dash_n_bang_ = function(obj,newVal) {
	 if (effect_colon_pick_dash_random_question_ (obj)) {
		obj.n = newVal;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_pick_dash_random_dash_n_bang_: not a effect:pick-random: ~s', [obj]));
     }
};

var set_dash_effect_colon_pick_dash_random_dash_update_dash_f_bang_ = function(obj,newVal) {
	 if (effect_colon_pick_dash_random_question_ (obj)) {
		obj.update_dash_f = newVal;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_pick_dash_random_dash_update_dash_f_bang_: not a effect:pick-random: ~s', [obj]));
     }
};

var effect_colon_pick_dash_random_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_pick_dash_random; };

var effect_question_ = function(thing) { return ((plt.Kernel.setLastLoc("offset=0 line=0 span=0 id=\"\"")   && effect_colon_none_question_(thing))||(plt.Kernel.setLastLoc("offset=0 line=0 span=0 id=\"\"")   && effect_colon_beep_question_(thing))||(plt.Kernel.setLastLoc("offset=0 line=0 span=0 id=\"\"")   && effect_colon_play_dash_dtmf_dash_tone_question_(thing))||(plt.Kernel.setLastLoc("offset=0 line=0 span=0 id=\"\"")   && effect_colon_send_dash_sms_question_(thing))||(plt.Kernel.setLastLoc("offset=0 line=0 span=0 id=\"\"")   && effect_colon_play_dash_sound_question_(thing))||(plt.Kernel.setLastLoc("offset=0 line=0 span=0 id=\"\"")   && effect_colon_pause_dash_sound_question_(thing))||(plt.Kernel.setLastLoc("offset=0 line=0 span=0 id=\"\"")   && effect_colon_stop_dash_sound_question_(thing))||(plt.Kernel.setLastLoc("offset=0 line=0 span=0 id=\"\"")   && effect_colon_set_dash_sound_dash_volume_question_(thing))||(plt.Kernel.setLastLoc("offset=0 line=0 span=0 id=\"\"")   && effect_colon_raise_dash_sound_dash_volume_question_(thing))||(plt.Kernel.setLastLoc("offset=0 line=0 span=0 id=\"\"")   && effect_colon_lower_dash_sound_dash_volume_question_(thing))||(plt.Kernel.setLastLoc("offset=0 line=0 span=0 id=\"\"")   && effect_colon_set_dash_wake_dash_lock_question_(thing))||(plt.Kernel.setLastLoc("offset=0 line=0 span=0 id=\"\"")   && effect_colon_release_dash_wake_dash_lock_question_(thing))||(plt.Kernel.setLastLoc("offset=0 line=0 span=0 id=\"\"")   && effect_colon_pick_dash_playlist_question_(thing))||(plt.Kernel.setLastLoc("offset=0 line=0 span=0 id=\"\"")   && effect_colon_pick_dash_random_question_(thing))); };
(function() { 
  ((function (toplevel_dash_expression_dash_show0) { 
















 })  )(arguments[0] || plt.Kernel.identity);
})();