// This is automatically generated by bootstrap-js-compiler.ss
// Please don't hand-edit this file.

var effect_colon_none = function () { plt.types.Struct.call(this, "make-effect:none", []); };
effect_colon_none.prototype = new plt.types.Struct();

var make_dash_effect_colon_none = function () { return new effect_colon_none(); };


var effect_colon_none_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_none; };

var effect_colon_beep = function () { plt.types.Struct.call(this, "make-effect:beep", []); };
effect_colon_beep.prototype = new plt.types.Struct();

var make_dash_effect_colon_beep = function () { return new effect_colon_beep(); };


var effect_colon_beep_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_beep; };

var effect_colon_play_dash_dtmf_dash_tone = function (tone,duration) { plt.types.Struct.call(this, "make-effect:play-dtmf-tone", [tone,duration]);this.tone = tone;
this.duration = duration; };
effect_colon_play_dash_dtmf_dash_tone.prototype = new plt.types.Struct();

var make_dash_effect_colon_play_dash_dtmf_dash_tone = function (id0,id1) { return new effect_colon_play_dash_dtmf_dash_tone(id0,id1); };
var effect_colon_play_dash_dtmf_dash_tone_dash_tone = function(obj) {
     if (effect_colon_play_dash_dtmf_dash_tone_question_ (obj)) {
        return obj.tone;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect:play-dtmf-tone-tone: not a effect:play-dtmf-tone: ~s', [obj]));
     }
};

var effect_colon_play_dash_dtmf_dash_tone_dash_duration = function(obj) {
     if (effect_colon_play_dash_dtmf_dash_tone_question_ (obj)) {
        return obj.duration;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect:play-dtmf-tone-duration: not a effect:play-dtmf-tone: ~s', [obj]));
     }
};

var set_dash_effect_colon_play_dash_dtmf_dash_tone_dash_tone_bang_ = function(obj,newVal) {
	 if (effect_colon_play_dash_dtmf_dash_tone_question_ (obj)) {
		obj.tone = newVal;
           obj._fields[0] = newVal;     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_play_dash_dtmf_dash_tone_dash_tone_bang_: not a effect:play-dtmf-tone: ~s', [obj]));
     }
};

var set_dash_effect_colon_play_dash_dtmf_dash_tone_dash_duration_bang_ = function(obj,newVal) {
	 if (effect_colon_play_dash_dtmf_dash_tone_question_ (obj)) {
		obj.duration = newVal;
           obj._fields[1] = newVal;     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_play_dash_dtmf_dash_tone_dash_duration_bang_: not a effect:play-dtmf-tone: ~s', [obj]));
     }
};

var effect_colon_play_dash_dtmf_dash_tone_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_play_dash_dtmf_dash_tone; };

var effect_colon_send_dash_sms = function (address,msg) { plt.types.Struct.call(this, "make-effect:send-sms", [address,msg]);this.address = address;
this.msg = msg; };
effect_colon_send_dash_sms.prototype = new plt.types.Struct();

var make_dash_effect_colon_send_dash_sms = function (id0,id1) { return new effect_colon_send_dash_sms(id0,id1); };
var effect_colon_send_dash_sms_dash_address = function(obj) {
     if (effect_colon_send_dash_sms_question_ (obj)) {
        return obj.address;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect:send-sms-address: not a effect:send-sms: ~s', [obj]));
     }
};

var effect_colon_send_dash_sms_dash_msg = function(obj) {
     if (effect_colon_send_dash_sms_question_ (obj)) {
        return obj.msg;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect:send-sms-msg: not a effect:send-sms: ~s', [obj]));
     }
};

var set_dash_effect_colon_send_dash_sms_dash_address_bang_ = function(obj,newVal) {
	 if (effect_colon_send_dash_sms_question_ (obj)) {
		obj.address = newVal;
           obj._fields[0] = newVal;     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_send_dash_sms_dash_address_bang_: not a effect:send-sms: ~s', [obj]));
     }
};

var set_dash_effect_colon_send_dash_sms_dash_msg_bang_ = function(obj,newVal) {
	 if (effect_colon_send_dash_sms_question_ (obj)) {
		obj.msg = newVal;
           obj._fields[1] = newVal;     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_send_dash_sms_dash_msg_bang_: not a effect:send-sms: ~s', [obj]));
     }
};

var effect_colon_send_dash_sms_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_send_dash_sms; };

var playlist_dash_sound = function (playlist) { plt.types.Struct.call(this, "make-playlist-sound", [playlist]);this.playlist = playlist; };
playlist_dash_sound.prototype = new plt.types.Struct();

var make_dash_playlist_dash_sound = function (id0) { return new playlist_dash_sound(id0); };
var playlist_dash_sound_dash_playlist = function(obj) {
     if (playlist_dash_sound_question_ (obj)) {
        return obj.playlist;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('playlist-sound-playlist: not a playlist-sound: ~s', [obj]));
     }
};

var set_dash_playlist_dash_sound_dash_playlist_bang_ = function(obj,newVal) {
	 if (playlist_dash_sound_question_ (obj)) {
		obj.playlist = newVal;
           obj._fields[0] = newVal;     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_playlist_dash_sound_dash_playlist_bang_: not a playlist-sound: ~s', [obj]));
     }
};

var playlist_dash_sound_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof playlist_dash_sound; };

var sound_question_ = function(x) { return ((plt.Kernel.setLastLoc({offset:417, line:19, span:11, id:"effect-struct.ss"})   && plt.Kernel.string_question_(x))||(plt.Kernel.setLastLoc({offset:435, line:20, span:19, id:"effect-struct.ss"})   && playlist_dash_sound_question_(x))); };
var effect_colon_play_dash_sound = function (sound) { plt.types.Struct.call(this, "make-effect:play-sound", [sound]);this.sound = sound; };
effect_colon_play_dash_sound.prototype = new plt.types.Struct();

var make_dash_effect_colon_play_dash_sound = function (id0) { return new effect_colon_play_dash_sound(id0); };
var effect_colon_play_dash_sound_dash_sound = function(obj) {
     if (effect_colon_play_dash_sound_question_ (obj)) {
        return obj.sound;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect:play-sound-sound: not a effect:play-sound: ~s', [obj]));
     }
};

var set_dash_effect_colon_play_dash_sound_dash_sound_bang_ = function(obj,newVal) {
	 if (effect_colon_play_dash_sound_question_ (obj)) {
		obj.sound = newVal;
           obj._fields[0] = newVal;     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_play_dash_sound_dash_sound_bang_: not a effect:play-sound: ~s', [obj]));
     }
};

var effect_colon_play_dash_sound_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_play_dash_sound; };

var effect_colon_pause_dash_sound = function (sound) { plt.types.Struct.call(this, "make-effect:pause-sound", [sound]);this.sound = sound; };
effect_colon_pause_dash_sound.prototype = new plt.types.Struct();

var make_dash_effect_colon_pause_dash_sound = function (id0) { return new effect_colon_pause_dash_sound(id0); };
var effect_colon_pause_dash_sound_dash_sound = function(obj) {
     if (effect_colon_pause_dash_sound_question_ (obj)) {
        return obj.sound;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect:pause-sound-sound: not a effect:pause-sound: ~s', [obj]));
     }
};

var set_dash_effect_colon_pause_dash_sound_dash_sound_bang_ = function(obj,newVal) {
	 if (effect_colon_pause_dash_sound_question_ (obj)) {
		obj.sound = newVal;
           obj._fields[0] = newVal;     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_pause_dash_sound_dash_sound_bang_: not a effect:pause-sound: ~s', [obj]));
     }
};

var effect_colon_pause_dash_sound_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_pause_dash_sound; };

var effect_colon_stop_dash_sound = function (sound) { plt.types.Struct.call(this, "make-effect:stop-sound", [sound]);this.sound = sound; };
effect_colon_stop_dash_sound.prototype = new plt.types.Struct();

var make_dash_effect_colon_stop_dash_sound = function (id0) { return new effect_colon_stop_dash_sound(id0); };
var effect_colon_stop_dash_sound_dash_sound = function(obj) {
     if (effect_colon_stop_dash_sound_question_ (obj)) {
        return obj.sound;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect:stop-sound-sound: not a effect:stop-sound: ~s', [obj]));
     }
};

var set_dash_effect_colon_stop_dash_sound_dash_sound_bang_ = function(obj,newVal) {
	 if (effect_colon_stop_dash_sound_question_ (obj)) {
		obj.sound = newVal;
           obj._fields[0] = newVal;     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_stop_dash_sound_dash_sound_bang_: not a effect:stop-sound: ~s', [obj]));
     }
};

var effect_colon_stop_dash_sound_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_stop_dash_sound; };

var effect_colon_set_dash_sound_dash_volume = function (volume) { plt.types.Struct.call(this, "make-effect:set-sound-volume", [volume]);this.volume = volume; };
effect_colon_set_dash_sound_dash_volume.prototype = new plt.types.Struct();

var make_dash_effect_colon_set_dash_sound_dash_volume = function (id0) { return new effect_colon_set_dash_sound_dash_volume(id0); };
var effect_colon_set_dash_sound_dash_volume_dash_volume = function(obj) {
     if (effect_colon_set_dash_sound_dash_volume_question_ (obj)) {
        return obj.volume;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect:set-sound-volume-volume: not a effect:set-sound-volume: ~s', [obj]));
     }
};

var set_dash_effect_colon_set_dash_sound_dash_volume_dash_volume_bang_ = function(obj,newVal) {
	 if (effect_colon_set_dash_sound_dash_volume_question_ (obj)) {
		obj.volume = newVal;
           obj._fields[0] = newVal;     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_set_dash_sound_dash_volume_dash_volume_bang_: not a effect:set-sound-volume: ~s', [obj]));
     }
};

var effect_colon_set_dash_sound_dash_volume_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_set_dash_sound_dash_volume; };

var effect_colon_raise_dash_sound_dash_volume = function () { plt.types.Struct.call(this, "make-effect:raise-sound-volume", []); };
effect_colon_raise_dash_sound_dash_volume.prototype = new plt.types.Struct();

var make_dash_effect_colon_raise_dash_sound_dash_volume = function () { return new effect_colon_raise_dash_sound_dash_volume(); };


var effect_colon_raise_dash_sound_dash_volume_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_raise_dash_sound_dash_volume; };

var effect_colon_lower_dash_sound_dash_volume = function () { plt.types.Struct.call(this, "make-effect:lower-sound-volume", []); };
effect_colon_lower_dash_sound_dash_volume.prototype = new plt.types.Struct();

var make_dash_effect_colon_lower_dash_sound_dash_volume = function () { return new effect_colon_lower_dash_sound_dash_volume(); };


var effect_colon_lower_dash_sound_dash_volume_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_lower_dash_sound_dash_volume; };

var effect_colon_set_dash_wake_dash_lock = function (locks) { plt.types.Struct.call(this, "make-effect:set-wake-lock", [locks]);this.locks = locks; };
effect_colon_set_dash_wake_dash_lock.prototype = new plt.types.Struct();

var make_dash_effect_colon_set_dash_wake_dash_lock = function (id0) { return new effect_colon_set_dash_wake_dash_lock(id0); };
var effect_colon_set_dash_wake_dash_lock_dash_locks = function(obj) {
     if (effect_colon_set_dash_wake_dash_lock_question_ (obj)) {
        return obj.locks;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect:set-wake-lock-locks: not a effect:set-wake-lock: ~s', [obj]));
     }
};

var set_dash_effect_colon_set_dash_wake_dash_lock_dash_locks_bang_ = function(obj,newVal) {
	 if (effect_colon_set_dash_wake_dash_lock_question_ (obj)) {
		obj.locks = newVal;
           obj._fields[0] = newVal;     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_set_dash_wake_dash_lock_dash_locks_bang_: not a effect:set-wake-lock: ~s', [obj]));
     }
};

var effect_colon_set_dash_wake_dash_lock_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_set_dash_wake_dash_lock; };

var effect_colon_release_dash_wake_dash_lock = function () { plt.types.Struct.call(this, "make-effect:release-wake-lock", []); };
effect_colon_release_dash_wake_dash_lock.prototype = new plt.types.Struct();

var make_dash_effect_colon_release_dash_wake_dash_lock = function () { return new effect_colon_release_dash_wake_dash_lock(); };


var effect_colon_release_dash_wake_dash_lock_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_release_dash_wake_dash_lock; };

var effect_colon_pick_dash_playlist = function (update_dash_f) { plt.types.Struct.call(this, "make-effect:pick-playlist", [update_dash_f]);this.update_dash_f = update_dash_f; };
effect_colon_pick_dash_playlist.prototype = new plt.types.Struct();

var make_dash_effect_colon_pick_dash_playlist = function (id0) { return new effect_colon_pick_dash_playlist(id0); };
var effect_colon_pick_dash_playlist_dash_update_dash_f = function(obj) {
     if (effect_colon_pick_dash_playlist_question_ (obj)) {
        return obj.update_dash_f;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect:pick-playlist-update-f: not a effect:pick-playlist: ~s', [obj]));
     }
};

var set_dash_effect_colon_pick_dash_playlist_dash_update_dash_f_bang_ = function(obj,newVal) {
	 if (effect_colon_pick_dash_playlist_question_ (obj)) {
		obj.update_dash_f = newVal;
           obj._fields[0] = newVal;     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_pick_dash_playlist_dash_update_dash_f_bang_: not a effect:pick-playlist: ~s', [obj]));
     }
};

var effect_colon_pick_dash_playlist_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_pick_dash_playlist; };

var effect_colon_pick_dash_random = function (n,update_dash_f) { plt.types.Struct.call(this, "make-effect:pick-random", [n,update_dash_f]);this.n = n;
this.update_dash_f = update_dash_f; };
effect_colon_pick_dash_random.prototype = new plt.types.Struct();

var make_dash_effect_colon_pick_dash_random = function (id0,id1) { return new effect_colon_pick_dash_random(id0,id1); };
var effect_colon_pick_dash_random_dash_n = function(obj) {
     if (effect_colon_pick_dash_random_question_ (obj)) {
        return obj.n;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect:pick-random-n: not a effect:pick-random: ~s', [obj]));
     }
};

var effect_colon_pick_dash_random_dash_update_dash_f = function(obj) {
     if (effect_colon_pick_dash_random_question_ (obj)) {
        return obj.update_dash_f;
     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('effect:pick-random-update-f: not a effect:pick-random: ~s', [obj]));
     }
};

var set_dash_effect_colon_pick_dash_random_dash_n_bang_ = function(obj,newVal) {
	 if (effect_colon_pick_dash_random_question_ (obj)) {
		obj.n = newVal;
           obj._fields[0] = newVal;     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_pick_dash_random_dash_n_bang_: not a effect:pick-random: ~s', [obj]));
     }
};

var set_dash_effect_colon_pick_dash_random_dash_update_dash_f_bang_ = function(obj,newVal) {
	 if (effect_colon_pick_dash_random_question_ (obj)) {
		obj.update_dash_f = newVal;
           obj._fields[1] = newVal;     } else {
        throw new plt.Kernel.MobyRuntimeError(            plt.Kernel.format('set_dash_effect_colon_pick_dash_random_dash_update_dash_f_bang_: not a effect:pick-random: ~s', [obj]));
     }
};

var effect_colon_pick_dash_random_question_ = function(obj) { 
              return obj != null && obj != undefined && obj instanceof effect_colon_pick_dash_random; };

var effect_question_ = function(thing) { return ((plt.Kernel.setLastLoc({offset:1069, line:43, span:20, id:"effect-struct.ss"})   && effect_colon_none_question_(thing))||(plt.Kernel.setLastLoc({offset:1096, line:44, span:20, id:"effect-struct.ss"})   && effect_colon_beep_question_(thing))||(plt.Kernel.setLastLoc({offset:1123, line:45, span:30, id:"effect-struct.ss"})   && effect_colon_play_dash_dtmf_dash_tone_question_(thing))||(plt.Kernel.setLastLoc({offset:1160, line:46, span:24, id:"effect-struct.ss"})   && effect_colon_send_dash_sms_question_(thing))||(plt.Kernel.setLastLoc({offset:1191, line:47, span:26, id:"effect-struct.ss"})   && effect_colon_play_dash_sound_question_(thing))||(plt.Kernel.setLastLoc({offset:1224, line:48, span:27, id:"effect-struct.ss"})   && effect_colon_pause_dash_sound_question_(thing))||(plt.Kernel.setLastLoc({offset:1258, line:49, span:26, id:"effect-struct.ss"})   && effect_colon_stop_dash_sound_question_(thing))||(plt.Kernel.setLastLoc({offset:1291, line:50, span:32, id:"effect-struct.ss"})   && effect_colon_set_dash_sound_dash_volume_question_(thing))||(plt.Kernel.setLastLoc({offset:1330, line:51, span:34, id:"effect-struct.ss"})   && effect_colon_raise_dash_sound_dash_volume_question_(thing))||(plt.Kernel.setLastLoc({offset:1371, line:52, span:34, id:"effect-struct.ss"})   && effect_colon_lower_dash_sound_dash_volume_question_(thing))||(plt.Kernel.setLastLoc({offset:1412, line:53, span:29, id:"effect-struct.ss"})   && effect_colon_set_dash_wake_dash_lock_question_(thing))||(plt.Kernel.setLastLoc({offset:1448, line:54, span:33, id:"effect-struct.ss"})   && effect_colon_release_dash_wake_dash_lock_question_(thing))||(plt.Kernel.setLastLoc({offset:1488, line:55, span:29, id:"effect-struct.ss"})   && effect_colon_pick_dash_playlist_question_(thing))||(plt.Kernel.setLastLoc({offset:1524, line:56, span:27, id:"effect-struct.ss"})   && effect_colon_pick_dash_random_question_(thing))); };
(function() { 
  ((function (toplevel_dash_expression_dash_show0) { 
















 })  )(arguments[0] || plt.Kernel.identity);
})();