/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.plt.Sketch;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int midpform=0x7f050000;
        public static final int midpgauge=0x7f050001;
        public static final int midpgauge_label=0x7f050002;
        public static final int midpgauge_progressbar=0x7f050003;
        public static final int midplist=0x7f050004;
        public static final int midplistitem=0x7f050005;
        public static final int midplistitem_image=0x7f050006;
        public static final int midplistitem_text=0x7f050007;
        public static final int midpstringitem=0x7f050008;
        public static final int midpstringitem_label=0x7f050009;
        public static final int midpstringitem_value=0x7f05000a;
    }
    public static final class layout {
        public static final int midpform=0x7f030000;
        public static final int midpgauge=0x7f030001;
        public static final int midplist=0x7f030002;
        public static final int midplistitem=0x7f030003;
        public static final int midpstringitem=0x7f030004;
        public static final int splash=0x7f030005;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
